'use client';

import { useState, useTransition } from 'react';
import { summarizeItemAction } from '@/app/app/actions';
import type { AiOutcome } from '@/lib/ai/outcome';

export default function AiSummary({ itemId, cached }: { itemId: string; cached: string | null }) {
  const [outcome, setOutcome] = useState<AiOutcome | null>(
    cached ? { status: 'ok', text: cached } : null
  );
  const [isPending, startTransition] = useTransition();

  if (outcome?.status === 'unavailable') return null;

  const summarize = () =>
    startTransition(async () => {
      setOutcome(await summarizeItemAction(itemId));
    });

  return (
    <section
      aria-labelledby='ai-summary'
      aria-busy={isPending}
      className='mt-6 rounded-lg border border-border-subtle bg-bg-secondary p-4'
    >
      <h2 id='ai-summary' className='flex items-center gap-2 text-sm font-semibold'>
        AI summary
        <span className='rounded bg-bg-tertiary px-1.5 text-xs font-medium text-text-secondary'>
          Generated by Claude
        </span>
      </h2>
      {isPending && (
        <div aria-hidden='true' className='mt-3 flex flex-col gap-2 motion-safe:animate-pulse'>
          <div className='h-3 rounded bg-bg-tertiary' />
          <div className='h-3 w-11/12 rounded bg-bg-tertiary' />
          <div className='h-3 w-4/5 rounded bg-bg-tertiary' />
        </div>
      )}
      <div role='status'>
        {isPending && <span className='sr-only'>Summarizing…</span>}
        {!isPending && outcome?.status === 'ok' && (
          <div className='mt-3 flex flex-col gap-3 text-base leading-relaxed'>
            {outcome.text.split(/\n\s*\n/).map((paragraph) => (
              <p key={paragraph}>{paragraph}</p>
            ))}
          </div>
        )}
        {!isPending && outcome?.status === 'limit' && (
          <p className='mt-2 text-sm text-text-secondary'>{outcome.message}</p>
        )}
      </div>
      {!isPending && outcome?.status !== 'ok' && (
        <button
          type='button'
          onClick={summarize}
          className='mt-3 min-h-11 rounded-md border border-border px-4 text-sm font-semibold hover:bg-bg-tertiary'
        >
          Summarize this article
        </button>
      )}
    </section>
  );
}
